modLoader="javafml"
loaderVersion="[47,)"
license="Universe3090 License"

[[mods]]
modId="universe3090"
version="1.5.0"
displayName="Universe3090-stories"
displayURL="https://nosite.com"
logoFile="logo.png"
credits="test version"
authors="wowa3090"
description="This Mod will add to your minecraft world items from Universe3090 And.. a lot of content"

[[dependencies.universe3090]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.universe3090]]
    modId="particlepresets"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

