
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.wowamod.init;

import net.wowamod.item.ZagatovkablackironItem;
import net.wowamod.item.YellowsoulpieceItem;
import net.wowamod.item.YellowsoulItem;
import net.wowamod.item.YellowemeraldItem;
import net.wowamod.item.YellowEmeraldPieceItem;
import net.wowamod.item.WowaswordosnovaItem;
import net.wowamod.item.WowaswordItem;
import net.wowamod.item.WowabronyaItem;
import net.wowamod.item.WiresprovodaItem;
import net.wowamod.item.WhitesoulMYPLACEItem;
import net.wowamod.item.WhiteemeraldItem;
import net.wowamod.item.WhiteEmeraldPieceItem;
import net.wowamod.item.SuperpalkaItem;
import net.wowamod.item.SoulsvazivatelItem;
import net.wowamod.item.SoulcoreItem;
import net.wowamod.item.SolarpanelelementItem;
import net.wowamod.item.ShadowbladeItem;
import net.wowamod.item.STBHswordItem;
import net.wowamod.item.RotorItem;
import net.wowamod.item.RoseItem;
import net.wowamod.item.RingItem;
import net.wowamod.item.RedsoulpieceItem;
import net.wowamod.item.RedsoulItem;
import net.wowamod.item.RedemeraldItem;
import net.wowamod.item.RedEmeraldPieceItem;
import net.wowamod.item.RainbowemeraldItem;
import net.wowamod.item.PurplesoulpieceItem;
import net.wowamod.item.PurplesoulItem;
import net.wowamod.item.PurpleemeraldItem;
import net.wowamod.item.PurpleEmeraldPieceItem;
import net.wowamod.item.PosudinaItem;
import net.wowamod.item.OsnovaaaaglassItem;
import net.wowamod.item.OrangesoulpieceItem;
import net.wowamod.item.OrangesoulItem;
import net.wowamod.item.NetherstarswordItem;
import net.wowamod.item.MyplacezoneItem;
import net.wowamod.item.MultitoolcomponentnottrueItem;
import net.wowamod.item.MultitoolcomponentItem;
import net.wowamod.item.MolotwowaItem;
import net.wowamod.item.MimictkanbItem;
import net.wowamod.item.MimickojaItem;
import net.wowamod.item.MagicironingotItem;
import net.wowamod.item.LightbluesoulpieceItem;
import net.wowamod.item.LightbluesoulItem;
import net.wowamod.item.LightblueemeraldItem;
import net.wowamod.item.LightBlueEmeraldPieceItem;
import net.wowamod.item.LaserguntestItem;
import net.wowamod.item.KolbaItem;
import net.wowamod.item.KlavaItem;
import net.wowamod.item.KarmannielectrolizerItem;
import net.wowamod.item.IzolationwItem;
import net.wowamod.item.IronplastinewowaItem;
import net.wowamod.item.Ironmass1Item;
import net.wowamod.item.InstrumentprostoItem;
import net.wowamod.item.GuidebookitemItem;
import net.wowamod.item.GreensoulpieceItem;
import net.wowamod.item.GreensoulItem;
import net.wowamod.item.GreenemeraldItem;
import net.wowamod.item.GreenEmeraldPieceItem;
import net.wowamod.item.GoldPlastineItem;
import net.wowamod.item.ExtractredsoulItem;
import net.wowamod.item.ExtractlbsoulItem;
import net.wowamod.item.ExtractgolubaysoulItem;
import net.wowamod.item.EtheriumdarkItem;
import net.wowamod.item.EnergyelementItem;
import net.wowamod.item.EkranchikItem;
import net.wowamod.item.DissasebmlyrequiredItem;
import net.wowamod.item.DerjatiliItem;
import net.wowamod.item.DarkironplastineItem;
import net.wowamod.item.CopperplateItem;
import net.wowamod.item.Coppermass1Item;
import net.wowamod.item.ClearetheriumlightItem;
import net.wowamod.item.BluesoulpieceItem;
import net.wowamod.item.BluesoulItem;
import net.wowamod.item.BlueemeraldItem;
import net.wowamod.item.BlueEmeraldPieceItem;
import net.wowamod.item.BlacksoulMYPLACEItem;
import net.wowamod.item.BlackironingotItem;
import net.wowamod.item.BatareykaItem;
import net.wowamod.item.AluminiumdiamondbaseItem;
import net.wowamod.item.AluminiumPlateItem;
import net.wowamod.item.AluminiumIngotItem;
import net.wowamod.item.AlphaelementItem;
import net.wowamod.item.AdarkplacesoundItem;
import net.wowamod.item.AaaGlassItem;
import net.wowamod.Universe3090Mod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class Universe3090ModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, Universe3090Mod.MODID);
	public static final RegistryObject<Item> WOWABRONYA_HELMET = REGISTRY.register("wowabronya_helmet", () -> new WowabronyaItem.Helmet());
	public static final RegistryObject<Item> WOWABRONYA_CHESTPLATE = REGISTRY.register("wowabronya_chestplate", () -> new WowabronyaItem.Chestplate());
	public static final RegistryObject<Item> WOWABRONYA_LEGGINGS = REGISTRY.register("wowabronya_leggings", () -> new WowabronyaItem.Leggings());
	public static final RegistryObject<Item> WOWABRONYA_BOOTS = REGISTRY.register("wowabronya_boots", () -> new WowabronyaItem.Boots());
	public static final RegistryObject<Item> NETHERSTARSWORD = REGISTRY.register("netherstarsword", () -> new NetherstarswordItem());
	public static final RegistryObject<Item> SHADOWBLADE = REGISTRY.register("shadowblade", () -> new ShadowbladeItem());
	public static final RegistryObject<Item> WOWASWORD = REGISTRY.register("wowasword", () -> new WowaswordItem());
	public static final RegistryObject<Item> GUIDEBOOKITEM = REGISTRY.register("guidebookitem", () -> new GuidebookitemItem());
	public static final RegistryObject<Item> SOULCORE = REGISTRY.register("soulcore", () -> new SoulcoreItem());
	public static final RegistryObject<Item> REDEMERALD = REGISTRY.register("redemerald", () -> new RedemeraldItem());
	public static final RegistryObject<Item> GREENEMERALD = REGISTRY.register("greenemerald", () -> new GreenemeraldItem());
	public static final RegistryObject<Item> BLUEEMERALD = REGISTRY.register("blueemerald", () -> new BlueemeraldItem());
	public static final RegistryObject<Item> LIGHTBLUEEMERALD = REGISTRY.register("lightblueemerald", () -> new LightblueemeraldItem());
	public static final RegistryObject<Item> PURPLEEMERALD = REGISTRY.register("purpleemerald", () -> new PurpleemeraldItem());
	public static final RegistryObject<Item> WHITEEMERALD = REGISTRY.register("whiteemerald", () -> new WhiteemeraldItem());
	public static final RegistryObject<Item> YELLOWEMERALD = REGISTRY.register("yellowemerald", () -> new YellowemeraldItem());
	public static final RegistryObject<Item> RAINBOWEMERALD = REGISTRY.register("rainbowemerald", () -> new RainbowemeraldItem());
	public static final RegistryObject<Item> REDSOUL = REGISTRY.register("redsoul", () -> new RedsoulItem());
	public static final RegistryObject<Item> ORANGESOUL = REGISTRY.register("orangesoul", () -> new OrangesoulItem());
	public static final RegistryObject<Item> YELLOWSOUL = REGISTRY.register("yellowsoul", () -> new YellowsoulItem());
	public static final RegistryObject<Item> GREENSOUL = REGISTRY.register("greensoul", () -> new GreensoulItem());
	public static final RegistryObject<Item> BLUESOUL = REGISTRY.register("bluesoul", () -> new BluesoulItem());
	public static final RegistryObject<Item> LIGHTBLUESOUL = REGISTRY.register("lightbluesoul", () -> new LightbluesoulItem());
	public static final RegistryObject<Item> PURPLESOUL = REGISTRY.register("purplesoul", () -> new PurplesoulItem());
	public static final RegistryObject<Item> REDSOULPIECE = REGISTRY.register("redsoulpiece", () -> new RedsoulpieceItem());
	public static final RegistryObject<Item> ORANGESOULPIECE = REGISTRY.register("orangesoulpiece", () -> new OrangesoulpieceItem());
	public static final RegistryObject<Item> YELLOWSOULPIECE = REGISTRY.register("yellowsoulpiece", () -> new YellowsoulpieceItem());
	public static final RegistryObject<Item> GREENSOULPIECE = REGISTRY.register("greensoulpiece", () -> new GreensoulpieceItem());
	public static final RegistryObject<Item> BLUESOULPIECE = REGISTRY.register("bluesoulpiece", () -> new BluesoulpieceItem());
	public static final RegistryObject<Item> LIGHTBLUESOULPIECE = REGISTRY.register("lightbluesoulpiece", () -> new LightbluesoulpieceItem());
	public static final RegistryObject<Item> PURPLESOULPIECE = REGISTRY.register("purplesoulpiece", () -> new PurplesoulpieceItem());
	public static final RegistryObject<Item> SOULSVAZIVATEL = REGISTRY.register("soulsvazivatel", () -> new SoulsvazivatelItem());
	public static final RegistryObject<Item> SUPERPALKA = REGISTRY.register("superpalka", () -> new SuperpalkaItem());
	public static final RegistryObject<Item> DERJATILI = REGISTRY.register("derjatili", () -> new DerjatiliItem());
	public static final RegistryObject<Item> MIMICTKANB = REGISTRY.register("mimictkanb", () -> new MimictkanbItem());
	public static final RegistryObject<Item> MIMICKOJA = REGISTRY.register("mimickoja", () -> new MimickojaItem());
	public static final RegistryObject<Item> ADARKPLACESOUND = REGISTRY.register("adarkplacesound", () -> new AdarkplacesoundItem());
	public static final RegistryObject<Item> DISSASEBMLYREQUIRED = REGISTRY.register("dissasebmlyrequired", () -> new DissasebmlyrequiredItem());
	public static final RegistryObject<Item> NIGHTMARE_SPAWN_EGG = REGISTRY.register("nightmare_spawn_egg", () -> new ForgeSpawnEggItem(Universe3090ModEntities.NIGHTMARE, -1, -52480, new Item.Properties()));
	public static final RegistryObject<Item> WOWASWORDOSNOVA = REGISTRY.register("wowaswordosnova", () -> new WowaswordosnovaItem());
	public static final RegistryObject<Item> EKRANCHIK = REGISTRY.register("ekranchik", () -> new EkranchikItem());
	public static final RegistryObject<Item> MAGICIRONINGOT = REGISTRY.register("magicironingot", () -> new MagicironingotItem());
	public static final RegistryObject<Item> EXTRACTLBSOUL = REGISTRY.register("extractlbsoul", () -> new ExtractlbsoulItem());
	public static final RegistryObject<Item> KOLBA = REGISTRY.register("kolba", () -> new KolbaItem());
	public static final RegistryObject<Item> EXTRACTGOLUBAYSOUL_BUCKET = REGISTRY.register("extractgolubaysoul_bucket", () -> new ExtractgolubaysoulItem());
	public static final RegistryObject<Item> KLAVA = REGISTRY.register("klava", () -> new KlavaItem());
	public static final RegistryObject<Item> ROTOR = REGISTRY.register("rotor", () -> new RotorItem());
	public static final RegistryObject<Item> EXTRACTREDSOUL = REGISTRY.register("extractredsoul", () -> new ExtractredsoulItem());
	public static final RegistryObject<Item> WHITESOUL_MYPLACE = REGISTRY.register("whitesoul_myplace", () -> new WhitesoulMYPLACEItem());
	public static final RegistryObject<Item> BLACKSOUL_MYPLACE = REGISTRY.register("blacksoul_myplace", () -> new BlacksoulMYPLACEItem());
	public static final RegistryObject<Item> AAA_GLASS = REGISTRY.register("aaa_glass", () -> new AaaGlassItem());
	public static final RegistryObject<Item> IRONMASS_1 = REGISTRY.register("ironmass_1", () -> new Ironmass1Item());
	public static final RegistryObject<Item> IRONPLASTINEWOWA = REGISTRY.register("ironplastinewowa", () -> new IronplastinewowaItem());
	public static final RegistryObject<Item> OSNOVAAAAGLASS = REGISTRY.register("osnovaaaaglass", () -> new OsnovaaaaglassItem());
	public static final RegistryObject<Item> BLACKIRONINGOT = REGISTRY.register("blackironingot", () -> new BlackironingotItem());
	public static final RegistryObject<Item> COPPERMASS_1 = REGISTRY.register("coppermass_1", () -> new Coppermass1Item());
	public static final RegistryObject<Item> WIRESPROVODA = REGISTRY.register("wiresprovoda", () -> new WiresprovodaItem());
	public static final RegistryObject<Item> INSTRUMENTPROSTO = REGISTRY.register("instrumentprosto", () -> new InstrumentprostoItem());
	public static final RegistryObject<Item> ALPHAELEMENT = REGISTRY.register("alphaelement", () -> new AlphaelementItem());
	public static final RegistryObject<Item> DARKGRASS = block(Universe3090ModBlocks.DARKGRASS);
	public static final RegistryObject<Item> DARKGRASSBLOCKNIZ = block(Universe3090ModBlocks.DARKGRASSBLOCKNIZ);
	public static final RegistryObject<Item> DARK_BIOME_ORE = block(Universe3090ModBlocks.DARK_BIOME_ORE);
	public static final RegistryObject<Item> ALUMINIUM_ORE_WOWA = block(Universe3090ModBlocks.ALUMINIUM_ORE_WOWA);
	public static final RegistryObject<Item> ETHERIUMDARK = REGISTRY.register("etheriumdark", () -> new EtheriumdarkItem());
	public static final RegistryObject<Item> BATAREYKA = REGISTRY.register("batareyka", () -> new BatareykaItem());
	public static final RegistryObject<Item> ZAGATOVKABLACKIRON = REGISTRY.register("zagatovkablackiron", () -> new ZagatovkablackironItem());
	public static final RegistryObject<Item> POSUDINA = REGISTRY.register("posudina", () -> new PosudinaItem());
	public static final RegistryObject<Item> KARMANNIELECTROLIZER = REGISTRY.register("karmannielectrolizer", () -> new KarmannielectrolizerItem());
	public static final RegistryObject<Item> MOLOTWOWA = REGISTRY.register("molotwowa", () -> new MolotwowaItem());
	public static final RegistryObject<Item> IZOLATIONW = REGISTRY.register("izolationw", () -> new IzolationwItem());
	public static final RegistryObject<Item> COPPERPLATE = REGISTRY.register("copperplate", () -> new CopperplateItem());
	public static final RegistryObject<Item> MULTITOOLCOMPONENT = REGISTRY.register("multitoolcomponent", () -> new MultitoolcomponentItem());
	public static final RegistryObject<Item> POGRANICHNIK = block(Universe3090ModBlocks.POGRANICHNIK);
	public static final RegistryObject<Item> DARK_STRK_BLK = block(Universe3090ModBlocks.DARK_STRK_BLK);
	public static final RegistryObject<Item> RED_EMERALD_PIECE = REGISTRY.register("red_emerald_piece", () -> new RedEmeraldPieceItem());
	public static final RegistryObject<Item> BLUE_EMERALD_PIECE = REGISTRY.register("blue_emerald_piece", () -> new BlueEmeraldPieceItem());
	public static final RegistryObject<Item> WHITE_EMERALD_PIECE = REGISTRY.register("white_emerald_piece", () -> new WhiteEmeraldPieceItem());
	public static final RegistryObject<Item> YELLOW_EMERALD_PIECE = REGISTRY.register("yellow_emerald_piece", () -> new YellowEmeraldPieceItem());
	public static final RegistryObject<Item> LIGHT_BLUE_EMERALD_PIECE = REGISTRY.register("light_blue_emerald_piece", () -> new LightBlueEmeraldPieceItem());
	public static final RegistryObject<Item> PURPLE_EMERALD_PIECE = REGISTRY.register("purple_emerald_piece", () -> new PurpleEmeraldPieceItem());
	public static final RegistryObject<Item> GREEN_EMERALD_PIECE = REGISTRY.register("green_emerald_piece", () -> new GreenEmeraldPieceItem());
	public static final RegistryObject<Item> ALUMINIUM_INGOT = REGISTRY.register("aluminium_ingot", () -> new AluminiumIngotItem());
	public static final RegistryObject<Item> ALUMINIUM_PLATE = REGISTRY.register("aluminium_plate", () -> new AluminiumPlateItem());
	public static final RegistryObject<Item> BLOCKFORPROFESSIAFIX = block(Universe3090ModBlocks.BLOCKFORPROFESSIAFIX);
	public static final RegistryObject<Item> CRAFTERBRONI = block(Universe3090ModBlocks.CRAFTERBRONI);
	public static final RegistryObject<Item> EMERALD_COMBINER = block(Universe3090ModBlocks.EMERALD_COMBINER);
	public static final RegistryObject<Item> BIG_BATTERYW = block(Universe3090ModBlocks.BIG_BATTERYW);
	public static final RegistryObject<Item> REDSTONECOMMANDBLOCK = block(Universe3090ModBlocks.REDSTONECOMMANDBLOCK);
	public static final RegistryObject<Item> MAGICIRONBLOCK = block(Universe3090ModBlocks.MAGICIRONBLOCK);
	public static final RegistryObject<Item> PORTCONSTRUCTOR = block(Universe3090ModBlocks.PORTCONSTRUCTOR);
	public static final RegistryObject<Item> INTERFACECONSTRUCTOR = block(Universe3090ModBlocks.INTERFACECONSTRUCTOR);
	public static final RegistryObject<Item> REDSTONEPORT = block(Universe3090ModBlocks.REDSTONEPORT);
	public static final RegistryObject<Item> EXTRACTOR = block(Universe3090ModBlocks.EXTRACTOR);
	public static final RegistryObject<Item> DARK_IRON_MACHINE_CASING = block(Universe3090ModBlocks.DARK_IRON_MACHINE_CASING);
	public static final RegistryObject<Item> DARKIRONPLASTINE = REGISTRY.register("darkironplastine", () -> new DarkironplastineItem());
	public static final RegistryObject<Item> ALUMINIUMDIAMONDBASE = REGISTRY.register("aluminiumdiamondbase", () -> new AluminiumdiamondbaseItem());
	public static final RegistryObject<Item> ENERGYELEMENT = REGISTRY.register("energyelement", () -> new EnergyelementItem());
	public static final RegistryObject<Item> MULTITOOLCOMPONENTNOTTRUE = REGISTRY.register("multitoolcomponentnottrue", () -> new MultitoolcomponentnottrueItem());
	public static final RegistryObject<Item> ROSE = REGISTRY.register("rose", () -> new RoseItem());
	public static final RegistryObject<Item> CORRUPTED_SOULS_BLOCK = block(Universe3090ModBlocks.CORRUPTED_SOULS_BLOCK);
	public static final RegistryObject<Item> BLACK_WALLS_MYPLACE = block(Universe3090ModBlocks.BLACK_WALLS_MYPLACE);
	public static final RegistryObject<Item> MYPLACEZONE = REGISTRY.register("myplacezone", () -> new MyplacezoneItem());
	public static final RegistryObject<Item> TRUEROSE = block(Universe3090ModBlocks.TRUEROSE);
	public static final RegistryObject<Item> SOLARPANELGENERATORW = block(Universe3090ModBlocks.SOLARPANELGENERATORW);
	public static final RegistryObject<Item> SOLARPANELELEMENT = REGISTRY.register("solarpanelelement", () -> new SolarpanelelementItem());
	public static final RegistryObject<Item> LASERGUNTEST = REGISTRY.register("laserguntest", () -> new LaserguntestItem());
	public static final RegistryObject<Item> CLEARETHERIUMLIGHT = REGISTRY.register("clearetheriumlight", () -> new ClearetheriumlightItem());
	public static final RegistryObject<Item> STB_HSWORD = REGISTRY.register("stb_hsword", () -> new STBHswordItem());
	public static final RegistryObject<Item> MIMIC_SPAWN_EGG = REGISTRY.register("mimic_spawn_egg", () -> new ForgeSpawnEggItem(Universe3090ModEntities.MIMIC, -10013184, -5131855, new Item.Properties()));
	public static final RegistryObject<Item> RING = REGISTRY.register("ring", () -> new RingItem());
	public static final RegistryObject<Item> TESTPLANT = block(Universe3090ModBlocks.TESTPLANT);
	public static final RegistryObject<Item> GOLD_PLASTINE = REGISTRY.register("gold_plastine", () -> new GoldPlastineItem());
	public static final RegistryObject<Item> CABLE_N = block(Universe3090ModBlocks.CABLE_N);
	public static final RegistryObject<Item> CABLE_E = block(Universe3090ModBlocks.CABLE_E);
	public static final RegistryObject<Item> CABLE_I = block(Universe3090ModBlocks.CABLE_I);
	public static final RegistryObject<Item> CABLE_F = block(Universe3090ModBlocks.CABLE_F);
	public static final RegistryObject<Item> CABLE_L = block(Universe3090ModBlocks.CABLE_L);
	public static final RegistryObject<Item> CABLE_LC = block(Universe3090ModBlocks.CABLE_LC);
	public static final RegistryObject<Item> CABLE_LCC = block(Universe3090ModBlocks.CABLE_LCC);
	public static final RegistryObject<Item> CABLE_LT = block(Universe3090ModBlocks.CABLE_LT);
	public static final RegistryObject<Item> CABLE_LTC = block(Universe3090ModBlocks.CABLE_LTC);
	public static final RegistryObject<Item> CABLE_T = block(Universe3090ModBlocks.CABLE_T);
	public static final RegistryObject<Item> CABLE_TC = block(Universe3090ModBlocks.CABLE_TC);
	public static final RegistryObject<Item> CABLE_TX = block(Universe3090ModBlocks.CABLE_TX);
	public static final RegistryObject<Item> CABLE_TXC = block(Universe3090ModBlocks.CABLE_TXC);
	public static final RegistryObject<Item> CABLE_TXCC = block(Universe3090ModBlocks.CABLE_TXCC);
	public static final RegistryObject<Item> CABLE_X = block(Universe3090ModBlocks.CABLE_X);
	public static final RegistryObject<Item> CABLE_XC = block(Universe3090ModBlocks.CABLE_XC);
	public static final RegistryObject<Item> CABLE_S = block(Universe3090ModBlocks.CABLE_S);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
