
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.wowamod.init;

import net.wowamod.item.ZagatovkablackironItem;
import net.wowamod.item.YellowsoulpieceItem;
import net.wowamod.item.YellowsoulItem;
import net.wowamod.item.YellowemeraldItem;
import net.wowamod.item.YellowEmeraldPieceItem;
import net.wowamod.item.WowaswordosnovaItem;
import net.wowamod.item.WowaswordItem;
import net.wowamod.item.WowabronyaItem;
import net.wowamod.item.WiresprovodaItem;
import net.wowamod.item.WillItem;
import net.wowamod.item.WhitesoulMYPLACEItem;
import net.wowamod.item.WhiteemeraldItem;
import net.wowamod.item.WhiteEmeraldPieceItem;
import net.wowamod.item.UltrastrongcoatingItem;
import net.wowamod.item.TheWelcomeCenterItem;
import net.wowamod.item.SuperpalkaItem;
import net.wowamod.item.SoulsvazivatelItem;
import net.wowamod.item.SoulcoreItem;
import net.wowamod.item.SoulcombineItem;
import net.wowamod.item.SosudItem;
import net.wowamod.item.SolarpanelelementItem;
import net.wowamod.item.ShantyoggItem;
import net.wowamod.item.ShadowbladeItem;
import net.wowamod.item.SealedvesseldiscItem;
import net.wowamod.item.STBHswordItem;
import net.wowamod.item.RotorItem;
import net.wowamod.item.RoseItem;
import net.wowamod.item.RingItem;
import net.wowamod.item.ResonateCrystalItem;
import net.wowamod.item.RedsoulpieceItem;
import net.wowamod.item.RedsoulItem;
import net.wowamod.item.RedemeraldItem;
import net.wowamod.item.ReddiamondmultitoolpluswItem;
import net.wowamod.item.ReddiamondlapisItem;
import net.wowamod.item.RedPlastineItem;
import net.wowamod.item.RedEmeraldPieceItem;
import net.wowamod.item.RedBronyaCoreItem;
import net.wowamod.item.RealityMachineItem;
import net.wowamod.item.RainbowemeraldItem;
import net.wowamod.item.PurplesoulpieceItem;
import net.wowamod.item.PurplesoulItem;
import net.wowamod.item.PurpleemeraldItem;
import net.wowamod.item.PurpleEmeraldPieceItem;
import net.wowamod.item.PosudinaItem;
import net.wowamod.item.PipesItem;
import net.wowamod.item.OsnovaaaaglassItem;
import net.wowamod.item.OrangesoulpieceItem;
import net.wowamod.item.OrangesoulItem;
import net.wowamod.item.NetherstarswordItem;
import net.wowamod.item.MyplacezoneItem;
import net.wowamod.item.MultitoolcomponentnottrueItem;
import net.wowamod.item.MultitoolcomponentItem;
import net.wowamod.item.MtwmodeorbitalItem;
import net.wowamod.item.MolotwowaItem;
import net.wowamod.item.MirrorComponentberilliumItem;
import net.wowamod.item.MimictkanbItem;
import net.wowamod.item.MimickojaItem;
import net.wowamod.item.MagicironingotItem;
import net.wowamod.item.MTWtestanimItem;
import net.wowamod.item.LightbluesoulpieceItem;
import net.wowamod.item.LightbluesoulItem;
import net.wowamod.item.LightblueemeraldItem;
import net.wowamod.item.LightBlueEmeraldPieceItem;
import net.wowamod.item.LifekolbaItem;
import net.wowamod.item.LepestkiRosyItem;
import net.wowamod.item.KolbaItem;
import net.wowamod.item.KlavaItem;
import net.wowamod.item.KarmannielectrolizerItem;
import net.wowamod.item.IzolationwItem;
import net.wowamod.item.IronplastinewowaItem;
import net.wowamod.item.Ironmass1Item;
import net.wowamod.item.InstrumentprostoItem;
import net.wowamod.item.GuidebookitemItem;
import net.wowamod.item.GreensoulpieceItem;
import net.wowamod.item.GreensoulItem;
import net.wowamod.item.GreenemeraldItem;
import net.wowamod.item.GreenEmeraldPieceItem;
import net.wowamod.item.GoldPlastineItem;
import net.wowamod.item.FirstbronyacomponentItem;
import net.wowamod.item.ExtractredsoulItem;
import net.wowamod.item.ExtractorangesoulItem;
import net.wowamod.item.ExtractlbsoulItem;
import net.wowamod.item.ExtractgolubaysoulItem;
import net.wowamod.item.ExtractbluesoulItem;
import net.wowamod.item.ExtractYellowSoulItem;
import net.wowamod.item.ExtractPurpleSoulItem;
import net.wowamod.item.ExtractGreenSoulItem;
import net.wowamod.item.EtheriumdarkItem;
import net.wowamod.item.EnergypipesuscItem;
import net.wowamod.item.EnergymagiccontrollerItem;
import net.wowamod.item.EnergyelementItem;
import net.wowamod.item.EmeraldspickaxeItem;
import net.wowamod.item.ElissclawItem;
import net.wowamod.item.ElissaarmorItem;
import net.wowamod.item.ElissClawsItem;
import net.wowamod.item.ElectromagiccoreItem;
import net.wowamod.item.EkranchikItem;
import net.wowamod.item.DissasebmlyrequiredItem;
import net.wowamod.item.DiamondlapistoolswordItem;
import net.wowamod.item.DiamondlapisItem;
import net.wowamod.item.Diamond_lapis_armorArmorItem;
import net.wowamod.item.DiamondMultiToolwItem;
import net.wowamod.item.DiamondLapisBronyaCpreItem;
import net.wowamod.item.DerjatiliItem;
import net.wowamod.item.DarkironplastineItem;
import net.wowamod.item.CopperplateItem;
import net.wowamod.item.Coppermass1Item;
import net.wowamod.item.CombinedAlloyItem;
import net.wowamod.item.ClearetheriumlightItem;
import net.wowamod.item.CharasknifeItem;
import net.wowamod.item.BluesoulpieceItem;
import net.wowamod.item.BluesoulItem;
import net.wowamod.item.BlueemeraldItem;
import net.wowamod.item.BlueEmeraldPieceItem;
import net.wowamod.item.BlacksoulMYPLACEItem;
import net.wowamod.item.BlackironingotItem;
import net.wowamod.item.BeyondtheBrightItem;
import net.wowamod.item.BerylstonechunkItem;
import net.wowamod.item.BerilliumCrystalItem;
import net.wowamod.item.BatareykaItem;
import net.wowamod.item.AluminiumdiamondbaseItem;
import net.wowamod.item.AluminiumPlateItem;
import net.wowamod.item.AluminiumIngotItem;
import net.wowamod.item.AlphaelementItem;
import net.wowamod.item.AdarkplacesoundItem;
import net.wowamod.item.AccessviolationItem;
import net.wowamod.item.AaaGlassItem;
import net.wowamod.Universe3090Mod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.ArmorItem;

public class Universe3090ModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, Universe3090Mod.MODID);
	public static final RegistryObject<Item> WOWABRONYA_HELMET = REGISTRY.register("wowabronya_helmet", () -> new WowabronyaItem.Helmet());
	public static final RegistryObject<Item> WOWABRONYA_CHESTPLATE = REGISTRY.register("wowabronya_chestplate", () -> new WowabronyaItem.Chestplate());
	public static final RegistryObject<Item> WOWABRONYA_LEGGINGS = REGISTRY.register("wowabronya_leggings", () -> new WowabronyaItem.Leggings());
	public static final RegistryObject<Item> WOWABRONYA_BOOTS = REGISTRY.register("wowabronya_boots", () -> new WowabronyaItem.Boots());
	public static final RegistryObject<Item> NETHERSTARSWORD = REGISTRY.register("netherstarsword", () -> new NetherstarswordItem());
	public static final RegistryObject<Item> SHADOWBLADE = REGISTRY.register("shadowblade", () -> new ShadowbladeItem());
	public static final RegistryObject<Item> WOWASWORD = REGISTRY.register("wowasword", () -> new WowaswordItem());
	public static final RegistryObject<Item> STB_HSWORD = REGISTRY.register("stb_hsword", () -> new STBHswordItem());
	public static final RegistryObject<Item> GUIDEBOOKITEM = REGISTRY.register("guidebookitem", () -> new GuidebookitemItem());
	public static final RegistryObject<Item> SOULCORE = REGISTRY.register("soulcore", () -> new SoulcoreItem());
	public static final RegistryObject<Item> YELLOWEMERALD = REGISTRY.register("yellowemerald", () -> new YellowemeraldItem());
	public static final RegistryObject<Item> GREENEMERALD = REGISTRY.register("greenemerald", () -> new GreenemeraldItem());
	public static final RegistryObject<Item> BLUEEMERALD = REGISTRY.register("blueemerald", () -> new BlueemeraldItem());
	public static final RegistryObject<Item> LIGHTBLUEEMERALD = REGISTRY.register("lightblueemerald", () -> new LightblueemeraldItem());
	public static final RegistryObject<Item> PURPLEEMERALD = REGISTRY.register("purpleemerald", () -> new PurpleemeraldItem());
	public static final RegistryObject<Item> WHITEEMERALD = REGISTRY.register("whiteemerald", () -> new WhiteemeraldItem());
	public static final RegistryObject<Item> REDEMERALD = REGISTRY.register("redemerald", () -> new RedemeraldItem());
	public static final RegistryObject<Item> RAINBOWEMERALD = REGISTRY.register("rainbowemerald", () -> new RainbowemeraldItem());
	public static final RegistryObject<Item> REDSOUL = REGISTRY.register("redsoul", () -> new RedsoulItem());
	public static final RegistryObject<Item> ORANGESOUL = REGISTRY.register("orangesoul", () -> new OrangesoulItem());
	public static final RegistryObject<Item> YELLOWSOUL = REGISTRY.register("yellowsoul", () -> new YellowsoulItem());
	public static final RegistryObject<Item> GREENSOUL = REGISTRY.register("greensoul", () -> new GreensoulItem());
	public static final RegistryObject<Item> BLUESOUL = REGISTRY.register("bluesoul", () -> new BluesoulItem());
	public static final RegistryObject<Item> LIGHTBLUESOUL = REGISTRY.register("lightbluesoul", () -> new LightbluesoulItem());
	public static final RegistryObject<Item> PURPLESOUL = REGISTRY.register("purplesoul", () -> new PurplesoulItem());
	public static final RegistryObject<Item> REDSOULPIECE = REGISTRY.register("redsoulpiece", () -> new RedsoulpieceItem());
	public static final RegistryObject<Item> ORANGESOULPIECE = REGISTRY.register("orangesoulpiece", () -> new OrangesoulpieceItem());
	public static final RegistryObject<Item> YELLOWSOULPIECE = REGISTRY.register("yellowsoulpiece", () -> new YellowsoulpieceItem());
	public static final RegistryObject<Item> GREENSOULPIECE = REGISTRY.register("greensoulpiece", () -> new GreensoulpieceItem());
	public static final RegistryObject<Item> BLUESOULPIECE = REGISTRY.register("bluesoulpiece", () -> new BluesoulpieceItem());
	public static final RegistryObject<Item> LIGHTBLUESOULPIECE = REGISTRY.register("lightbluesoulpiece", () -> new LightbluesoulpieceItem());
	public static final RegistryObject<Item> PURPLESOULPIECE = REGISTRY.register("purplesoulpiece", () -> new PurplesoulpieceItem());
	public static final RegistryObject<Item> SOULSVAZIVATEL = REGISTRY.register("soulsvazivatel", () -> new SoulsvazivatelItem());
	public static final RegistryObject<Item> SUPERPALKA = REGISTRY.register("superpalka", () -> new SuperpalkaItem());
	public static final RegistryObject<Item> DERJATILI = REGISTRY.register("derjatili", () -> new DerjatiliItem());
	public static final RegistryObject<Item> MIMICTKANB = REGISTRY.register("mimictkanb", () -> new MimictkanbItem());
	public static final RegistryObject<Item> MIMICKOJA = REGISTRY.register("mimickoja", () -> new MimickojaItem());
	public static final RegistryObject<Item> NIGHTMARE_SPAWN_EGG = REGISTRY.register("nightmare_spawn_egg", () -> new ForgeSpawnEggItem(Universe3090ModEntities.NIGHTMARE, -1, -52480, new Item.Properties()));
	public static final RegistryObject<Item> WOWASWORDOSNOVA = REGISTRY.register("wowaswordosnova", () -> new WowaswordosnovaItem());
	public static final RegistryObject<Item> EKRANCHIK = REGISTRY.register("ekranchik", () -> new EkranchikItem());
	public static final RegistryObject<Item> MAGICIRONINGOT = REGISTRY.register("magicironingot", () -> new MagicironingotItem());
	public static final RegistryObject<Item> EXTRACTGOLUBAYSOUL_BUCKET = REGISTRY.register("extractgolubaysoul_bucket", () -> new ExtractgolubaysoulItem());
	public static final RegistryObject<Item> KLAVA = REGISTRY.register("klava", () -> new KlavaItem());
	public static final RegistryObject<Item> ROTOR = REGISTRY.register("rotor", () -> new RotorItem());
	public static final RegistryObject<Item> WHITESOUL_MYPLACE = REGISTRY.register("whitesoul_myplace", () -> new WhitesoulMYPLACEItem());
	public static final RegistryObject<Item> BLACKSOUL_MYPLACE = REGISTRY.register("blacksoul_myplace", () -> new BlacksoulMYPLACEItem());
	public static final RegistryObject<Item> AAA_GLASS = REGISTRY.register("aaa_glass", () -> new AaaGlassItem());
	public static final RegistryObject<Item> IRONMASS_1 = REGISTRY.register("ironmass_1", () -> new Ironmass1Item());
	public static final RegistryObject<Item> IRONPLASTINEWOWA = REGISTRY.register("ironplastinewowa", () -> new IronplastinewowaItem());
	public static final RegistryObject<Item> OSNOVAAAAGLASS = REGISTRY.register("osnovaaaaglass", () -> new OsnovaaaaglassItem());
	public static final RegistryObject<Item> BLACKIRONINGOT = REGISTRY.register("blackironingot", () -> new BlackironingotItem());
	public static final RegistryObject<Item> COPPERMASS_1 = REGISTRY.register("coppermass_1", () -> new Coppermass1Item());
	public static final RegistryObject<Item> WIRESPROVODA = REGISTRY.register("wiresprovoda", () -> new WiresprovodaItem());
	public static final RegistryObject<Item> INSTRUMENTPROSTO = REGISTRY.register("instrumentprosto", () -> new InstrumentprostoItem());
	public static final RegistryObject<Item> ALPHAELEMENT = REGISTRY.register("alphaelement", () -> new AlphaelementItem());
	public static final RegistryObject<Item> DARKGRASS = block(Universe3090ModBlocks.DARKGRASS);
	public static final RegistryObject<Item> DARKGRASSBLOCKNIZ = block(Universe3090ModBlocks.DARKGRASSBLOCKNIZ);
	public static final RegistryObject<Item> DARK_BIOME_ORE = block(Universe3090ModBlocks.DARK_BIOME_ORE);
	public static final RegistryObject<Item> ALUMINIUM_ORE_WOWA = block(Universe3090ModBlocks.ALUMINIUM_ORE_WOWA);
	public static final RegistryObject<Item> ETHERIUMDARK = REGISTRY.register("etheriumdark", () -> new EtheriumdarkItem());
	public static final RegistryObject<Item> BATAREYKA = REGISTRY.register("batareyka", () -> new BatareykaItem());
	public static final RegistryObject<Item> ZAGATOVKABLACKIRON = REGISTRY.register("zagatovkablackiron", () -> new ZagatovkablackironItem());
	public static final RegistryObject<Item> POSUDINA = REGISTRY.register("posudina", () -> new PosudinaItem());
	public static final RegistryObject<Item> KARMANNIELECTROLIZER = REGISTRY.register("karmannielectrolizer", () -> new KarmannielectrolizerItem());
	public static final RegistryObject<Item> MOLOTWOWA = REGISTRY.register("molotwowa", () -> new MolotwowaItem());
	public static final RegistryObject<Item> IZOLATIONW = REGISTRY.register("izolationw", () -> new IzolationwItem());
	public static final RegistryObject<Item> COPPERPLATE = REGISTRY.register("copperplate", () -> new CopperplateItem());
	public static final RegistryObject<Item> MULTITOOLCOMPONENT = REGISTRY.register("multitoolcomponent", () -> new MultitoolcomponentItem());
	public static final RegistryObject<Item> POGRANICHNIK = block(Universe3090ModBlocks.POGRANICHNIK);
	public static final RegistryObject<Item> DARK_STRK_BLK = block(Universe3090ModBlocks.DARK_STRK_BLK);
	public static final RegistryObject<Item> RED_EMERALD_PIECE = REGISTRY.register("red_emerald_piece", () -> new RedEmeraldPieceItem());
	public static final RegistryObject<Item> BLUE_EMERALD_PIECE = REGISTRY.register("blue_emerald_piece", () -> new BlueEmeraldPieceItem());
	public static final RegistryObject<Item> WHITE_EMERALD_PIECE = REGISTRY.register("white_emerald_piece", () -> new WhiteEmeraldPieceItem());
	public static final RegistryObject<Item> YELLOW_EMERALD_PIECE = REGISTRY.register("yellow_emerald_piece", () -> new YellowEmeraldPieceItem());
	public static final RegistryObject<Item> LIGHT_BLUE_EMERALD_PIECE = REGISTRY.register("light_blue_emerald_piece", () -> new LightBlueEmeraldPieceItem());
	public static final RegistryObject<Item> PURPLE_EMERALD_PIECE = REGISTRY.register("purple_emerald_piece", () -> new PurpleEmeraldPieceItem());
	public static final RegistryObject<Item> GREEN_EMERALD_PIECE = REGISTRY.register("green_emerald_piece", () -> new GreenEmeraldPieceItem());
	public static final RegistryObject<Item> ALUMINIUM_INGOT = REGISTRY.register("aluminium_ingot", () -> new AluminiumIngotItem());
	public static final RegistryObject<Item> ALUMINIUM_PLATE = REGISTRY.register("aluminium_plate", () -> new AluminiumPlateItem());
	public static final RegistryObject<Item> BLOCKFORPROFESSIAFIX = block(Universe3090ModBlocks.BLOCKFORPROFESSIAFIX);
	public static final RegistryObject<Item> CRAFTERBRONI = block(Universe3090ModBlocks.CRAFTERBRONI);
	public static final RegistryObject<Item> EMERALD_COMBINER = block(Universe3090ModBlocks.EMERALD_COMBINER);
	public static final RegistryObject<Item> BIG_BATTERYW = block(Universe3090ModBlocks.BIG_BATTERYW);
	public static final RegistryObject<Item> REDSTONECOMMANDBLOCK = block(Universe3090ModBlocks.REDSTONECOMMANDBLOCK);
	public static final RegistryObject<Item> MAGICIRONBLOCK = block(Universe3090ModBlocks.MAGICIRONBLOCK);
	public static final RegistryObject<Item> PORTCONSTRUCTOR = block(Universe3090ModBlocks.PORTCONSTRUCTOR);
	public static final RegistryObject<Item> INTERFACECONSTRUCTOR = block(Universe3090ModBlocks.INTERFACECONSTRUCTOR);
	public static final RegistryObject<Item> REDSTONEPORT = block(Universe3090ModBlocks.REDSTONEPORT);
	public static final RegistryObject<Item> EXTRACTOR = block(Universe3090ModBlocks.EXTRACTOR);
	public static final RegistryObject<Item> DARK_IRON_MACHINE_CASING = block(Universe3090ModBlocks.DARK_IRON_MACHINE_CASING);
	public static final RegistryObject<Item> SOLARPANELGENERATORW = block(Universe3090ModBlocks.SOLARPANELGENERATORW);
	public static final RegistryObject<Item> DARKIRONPLASTINE = REGISTRY.register("darkironplastine", () -> new DarkironplastineItem());
	public static final RegistryObject<Item> ALUMINIUMDIAMONDBASE = REGISTRY.register("aluminiumdiamondbase", () -> new AluminiumdiamondbaseItem());
	public static final RegistryObject<Item> ENERGYELEMENT = REGISTRY.register("energyelement", () -> new EnergyelementItem());
	public static final RegistryObject<Item> MULTITOOLCOMPONENTNOTTRUE = REGISTRY.register("multitoolcomponentnottrue", () -> new MultitoolcomponentnottrueItem());
	public static final RegistryObject<Item> SOLARPANELELEMENT = REGISTRY.register("solarpanelelement", () -> new SolarpanelelementItem());
	public static final RegistryObject<Item> CLEARETHERIUMLIGHT = REGISTRY.register("clearetheriumlight", () -> new ClearetheriumlightItem());
	public static final RegistryObject<Item> MIMIC_SPAWN_EGG = REGISTRY.register("mimic_spawn_egg", () -> new ForgeSpawnEggItem(Universe3090ModEntities.MIMIC, -10013184, -5131855, new Item.Properties()));
	public static final RegistryObject<Item> RING = REGISTRY.register("ring", () -> new RingItem());
	public static final RegistryObject<Item> GOLD_PLASTINE = REGISTRY.register("gold_plastine", () -> new GoldPlastineItem());
	public static final RegistryObject<Item> TESTPLANT = block(Universe3090ModBlocks.TESTPLANT);
	public static final RegistryObject<Item> CABLE_N = block(Universe3090ModBlocks.CABLE_N);
	public static final RegistryObject<Item> DIAMOND_MULTI_TOOLW = REGISTRY.register("diamond_multi_toolw", () -> new DiamondMultiToolwItem());
	public static final RegistryObject<Item> DIAMONDLAPIS = REGISTRY.register("diamondlapis", () -> new DiamondlapisItem());
	public static final RegistryObject<Item> DIAMONDLAPISBLOCK = block(Universe3090ModBlocks.DIAMONDLAPISBLOCK);
	public static final RegistryObject<Item> REDDIAMONDMULTITOOLPLUSW = REGISTRY.register("reddiamondmultitoolplusw", () -> new ReddiamondmultitoolpluswItem());
	public static final RegistryObject<Item> REDDIAMONDLAPIS = REGISTRY.register("reddiamondlapis", () -> new ReddiamondlapisItem());
	public static final RegistryObject<Item> DIAMOND_LAPIS_ARMOR_ARMOR_HELMET = REGISTRY.register("diamond_lapis_armor_armor_helmet", () -> new Diamond_lapis_armorArmorItem.Helmet());
	public static final RegistryObject<Item> DIAMOND_LAPIS_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("diamond_lapis_armor_armor_chestplate", () -> new Diamond_lapis_armorArmorItem.Chestplate());
	public static final RegistryObject<Item> DIAMOND_LAPIS_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("diamond_lapis_armor_armor_leggings", () -> new Diamond_lapis_armorArmorItem.Leggings());
	public static final RegistryObject<Item> DIAMOND_LAPIS_ARMOR_ARMOR_BOOTS = REGISTRY.register("diamond_lapis_armor_armor_boots", () -> new Diamond_lapis_armorArmorItem.Boots());
	public static final RegistryObject<Item> DIAMOND_LAPIS_BRONYA_CPRE = REGISTRY.register("diamond_lapis_bronya_cpre", () -> new DiamondLapisBronyaCpreItem());
	public static final RegistryObject<Item> DIAMONDLAPISTOOLSWORD = REGISTRY.register("diamondlapistoolsword", () -> new DiamondlapistoolswordItem());
	public static final RegistryObject<Item> MT_WTESTANIM = REGISTRY.register("mt_wtestanim", () -> new MTWtestanimItem());
	public static final RegistryObject<ElissaarmorItem> ELISSAARMOR_HELMET = REGISTRY.register("elissaarmor_helmet", () -> new ElissaarmorItem(ArmorItem.Type.HELMET, new Item.Properties()));
	public static final RegistryObject<ElissaarmorItem> ELISSAARMOR_CHESTPLATE = REGISTRY.register("elissaarmor_chestplate", () -> new ElissaarmorItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<ElissaarmorItem> ELISSAARMOR_LEGGINGS = REGISTRY.register("elissaarmor_leggings", () -> new ElissaarmorItem(ArmorItem.Type.LEGGINGS, new Item.Properties()));
	public static final RegistryObject<ElissaarmorItem> ELISSAARMOR_BOOTS = REGISTRY.register("elissaarmor_boots", () -> new ElissaarmorItem(ArmorItem.Type.BOOTS, new Item.Properties()));
	public static final RegistryObject<Item> ELISS_CLAWS = REGISTRY.register("eliss_claws", () -> new ElissClawsItem());
	public static final RegistryObject<Item> ELISSCLAW = REGISTRY.register("elissclaw", () -> new ElissclawItem());
	public static final RegistryObject<Item> ULTRASTRONGCOATING = REGISTRY.register("ultrastrongcoating", () -> new UltrastrongcoatingItem());
	public static final RegistryObject<Item> ENERGYPIPESUSC = REGISTRY.register("energypipesusc", () -> new EnergypipesuscItem());
	public static final RegistryObject<Item> PIPES = REGISTRY.register("pipes", () -> new PipesItem());
	public static final RegistryObject<Item> ENERGYMAGICCONTROLLER = REGISTRY.register("energymagiccontroller", () -> new EnergymagiccontrollerItem());
	public static final RegistryObject<Item> ELECTROMAGICCORE = REGISTRY.register("electromagiccore", () -> new ElectromagiccoreItem());
	public static final RegistryObject<Item> FIRSTBRONYACOMPONENT = REGISTRY.register("firstbronyacomponent", () -> new FirstbronyacomponentItem());
	public static final RegistryObject<Item> DARKIRONBLOCK = block(Universe3090ModBlocks.DARKIRONBLOCK);
	public static final RegistryObject<Item> MTWMODEORBITAL = REGISTRY.register("mtwmodeorbital", () -> new MtwmodeorbitalItem());
	public static final RegistryObject<Item> RED_BRONYA_CORE = REGISTRY.register("red_bronya_core", () -> new RedBronyaCoreItem());
	public static final RegistryObject<Item> RED_PLASTINE = REGISTRY.register("red_plastine", () -> new RedPlastineItem());
	public static final RegistryObject<Item> REDEMPTYCORE = block(Universe3090ModBlocks.REDEMPTYCORE);
	public static final RegistryObject<Item> REDCORE = block(Universe3090ModBlocks.REDCORE);
	public static final RegistryObject<Item> BERILLIUM = block(Universe3090ModBlocks.BERILLIUM);
	public static final RegistryObject<Item> BERILLIUM_CRYSTAL = REGISTRY.register("berillium_crystal", () -> new BerilliumCrystalItem());
	public static final RegistryObject<Item> KOLBA = REGISTRY.register("kolba", () -> new KolbaItem());
	public static final RegistryObject<Item> EXTRACTLBSOUL = REGISTRY.register("extractlbsoul", () -> new ExtractlbsoulItem());
	public static final RegistryObject<Item> EXTRACTREDSOUL = REGISTRY.register("extractredsoul", () -> new ExtractredsoulItem());
	public static final RegistryObject<Item> EXTRACTORANGESOUL = REGISTRY.register("extractorangesoul", () -> new ExtractorangesoulItem());
	public static final RegistryObject<Item> EXTRACT_GREEN_SOUL = REGISTRY.register("extract_green_soul", () -> new ExtractGreenSoulItem());
	public static final RegistryObject<Item> EXTRACT_PURPLE_SOUL = REGISTRY.register("extract_purple_soul", () -> new ExtractPurpleSoulItem());
	public static final RegistryObject<Item> EXTRACT_YELLOW_SOUL = REGISTRY.register("extract_yellow_soul", () -> new ExtractYellowSoulItem());
	public static final RegistryObject<Item> EXTRACTBLUESOUL = REGISTRY.register("extractbluesoul", () -> new ExtractbluesoulItem());
	public static final RegistryObject<Item> COMBINED_ALLOY = REGISTRY.register("combined_alloy", () -> new CombinedAlloyItem());
	public static final RegistryObject<Item> SMELTERBLOCK = block(Universe3090ModBlocks.SMELTERBLOCK);
	public static final RegistryObject<Item> MIRROR_COMPONENTBERILLIUM = REGISTRY.register("mirror_componentberillium", () -> new MirrorComponentberilliumItem());
	public static final RegistryObject<Item> BERILLIUMDEEPSLATE = block(Universe3090ModBlocks.BERILLIUMDEEPSLATE);
	public static final RegistryObject<Item> WILL = REGISTRY.register("will", () -> new WillItem());
	public static final RegistryObject<Item> LIFEKOLBA = REGISTRY.register("lifekolba", () -> new LifekolbaItem());
	public static final RegistryObject<Item> SOULCOMBINE = REGISTRY.register("soulcombine", () -> new SoulcombineItem());
	public static final RegistryObject<Item> SOSUD = REGISTRY.register("sosud", () -> new SosudItem());
	public static final RegistryObject<Item> ROSE_IN_JAR = block(Universe3090ModBlocks.ROSE_IN_JAR);
	public static final RegistryObject<Item> REDSTONE_9X = block(Universe3090ModBlocks.REDSTONE_9X);
	public static final RegistryObject<Item> CHARASKNIFE = REGISTRY.register("charasknife", () -> new CharasknifeItem());
	public static final RegistryObject<Item> ADARKPLACESOUND = REGISTRY.register("adarkplacesound", () -> new AdarkplacesoundItem());
	public static final RegistryObject<Item> DISSASEBMLYREQUIRED = REGISTRY.register("dissasebmlyrequired", () -> new DissasebmlyrequiredItem());
	public static final RegistryObject<Item> ROSE = REGISTRY.register("rose", () -> new RoseItem());
	public static final RegistryObject<Item> CORRUPTED_SOULS_BLOCK = block(Universe3090ModBlocks.CORRUPTED_SOULS_BLOCK);
	public static final RegistryObject<Item> BLACK_WALLS_MYPLACE = block(Universe3090ModBlocks.BLACK_WALLS_MYPLACE);
	public static final RegistryObject<Item> MYPLACEZONE = REGISTRY.register("myplacezone", () -> new MyplacezoneItem());
	public static final RegistryObject<Item> TRUEROSE = block(Universe3090ModBlocks.TRUEROSE);
	public static final RegistryObject<Item> DARK_HEAD_SPAWN_EGG = REGISTRY.register("dark_head_spawn_egg", () -> new ForgeSpawnEggItem(Universe3090ModEntities.DARK_HEAD, -16777216, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> BEYONDTHE_BRIGHT = REGISTRY.register("beyondthe_bright", () -> new BeyondtheBrightItem());
	public static final RegistryObject<Item> REALITY_MACHINE = REGISTRY.register("reality_machine", () -> new RealityMachineItem());
	public static final RegistryObject<Item> ACCESSVIOLATION = REGISTRY.register("accessviolation", () -> new AccessviolationItem());
	public static final RegistryObject<Item> THE_WELCOME_CENTER = REGISTRY.register("the_welcome_center", () -> new TheWelcomeCenterItem());
	public static final RegistryObject<Item> BLACKWALLSMYPLACESLAB = block(Universe3090ModBlocks.BLACKWALLSMYPLACESLAB);
	public static final RegistryObject<Item> LEPESTKI_ROSY = REGISTRY.register("lepestki_rosy", () -> new LepestkiRosyItem());
	public static final RegistryObject<Item> SHANTYOGG = REGISTRY.register("shantyogg", () -> new ShantyoggItem());
	public static final RegistryObject<Item> SEALEDVESSELDISC = REGISTRY.register("sealedvesseldisc", () -> new SealedvesseldiscItem());
	public static final RegistryObject<Item> CABLE_E = block(Universe3090ModBlocks.CABLE_E);
	public static final RegistryObject<Item> BERYLSTONECHUNK = REGISTRY.register("berylstonechunk", () -> new BerylstonechunkItem());
	public static final RegistryObject<Item> REDEMERALDCRYSTAL = block(Universe3090ModBlocks.REDEMERALDCRYSTAL);
	public static final RegistryObject<Item> BLUEEMERALDCRYSTAL = block(Universe3090ModBlocks.BLUEEMERALDCRYSTAL);
	public static final RegistryObject<Item> GREENEMERALDCRYSTAL = block(Universe3090ModBlocks.GREENEMERALDCRYSTAL);
	public static final RegistryObject<Item> YELLOWEMERALDCRYSTAL = block(Universe3090ModBlocks.YELLOWEMERALDCRYSTAL);
	public static final RegistryObject<Item> PURPLEEMERALDCRYSTAL = block(Universe3090ModBlocks.PURPLEEMERALDCRYSTAL);
	public static final RegistryObject<Item> WHITEEMERALDCRYSTAL = block(Universe3090ModBlocks.WHITEEMERALDCRYSTAL);
	public static final RegistryObject<Item> LIGHTBLUEEMERALDCRYSTAL = block(Universe3090ModBlocks.LIGHTBLUEEMERALDCRYSTAL);
	public static final RegistryObject<Item> RESONATE_CRYSTAL = REGISTRY.register("resonate_crystal", () -> new ResonateCrystalItem());
	public static final RegistryObject<Item> EMERALDSPICKAXE = REGISTRY.register("emeraldspickaxe", () -> new EmeraldspickaxeItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
